Version = "0.0.1"

[Bot]
Debug = true
Timeout = 60 # sec
TeplatePath = "internal/commander/template/"

[Database]
DriverName = "postgres"
Addr = "localhost"
Username = "paimon"
Password = "paimon"
Database = "paimoncookies"